### ISSUE TITLE
Sane syntax for intervals

### ISSUE THREAD

**Issue by phoe** [tsikov/clerk#1]
Currently the intervals taken are in form `5.seconds`, which is a symbol and prevents me from using numerical values.

I request the ability to pass intervals in form `(5 :seconds)` or similar, which is a list or cons of two values, one of which is numerical and the other is time unit - perhaps optional, defaulting to seconds.

**Comment by tsikov** [comment]
I like it. My original idea was that the library will be used as an execution of some sort of configuration file. However with your idea the library can be used programatically. Neat. I will post in the thread when I am ready with your request 👍

**Comment by tsikov** [comment]
@phoe On second thought there is a bit of a problem. The `job` operator is implemented as a macro. This is what allows us to use `every` and `5.seconds` as if they were variables. When the macro is expanded they are interpreted as symbols. If it was a function, lisp would've been giving us errors.

Perhaps what I can do is expose (export) the underlying function `add-to-jobs-queue` and implement another function (e.g. `interval-list->interval`) that converts an interval list like the one you proposed to an interval that can be understood by the `job` macro.

Then you will be able to write something like:

```
(defparamter +query-interval+ 5)
(add-to-jobs-queue "Query the API every 5 seconds"
                   'every
                   (interval-list-> interval (list +query-interval 'seconds))
                   (dex:get "https://awesome-api.com/v1/..."))
```

Thoughts?

P.S. Thank you for your interest in the project!

**Comment by tsikov** [comment]
Actually, now that I think about it, it would be even easier if I implement functions like `continuous-job` and `one-time-job` that just call `add-to-jobs-queue` internally :) So you will be able to write something like

```
(continuos-job (5 :seconds) (call-to-api) :name "API call")
(one-time-job :monday (send-report))
```

And the `name` keyword will be optional.

**Comment by phoe** [comment]
Yes, pretty please. Anything that allows me to go `(5 :seconds)` will do the job here.

**Comment by tsikov** [comment]
@phoe [I implemented](https://github.com/tsikov/clerk#job-function) the requested functionality. Can you please confirm if this is what you wanted?

You can still use the `job` macro for intervals like `'(5 seconds)`, but you must use the function `job-fn` if you want to use a variable for the numbers or type interval. E.g.: `(list +number-of-seconds+ seconds)`

**Comment by phoe** [comment]
Sure!
Is the `'every` required there though? Why not make it a keyword instead to avoid problems with importing symbols?

**Comment by tsikov** [comment]
@phoe I haven't tested it, but you can use `:every` if you want. The symbol that dictates if the job is continuous is only used inside `continuous-p` predicate and it uses `string=` for comparison. `string=` can compare symbols, but it ignores the packages, in essence doing package agnostic symbol comparison. :)

**Comment by phoe** [comment]
Good. I think this issue is closeable then.
